apiVersion: v1
kind: Service
metadata:
  name: payments-service-service
spec:
  type: LoadBalancer
  selector:
    app: payments-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080